### ISSUE TITLE
latest bc2pg bails on crown tenures

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#110]
```
$ bcdata bc2pg whse_tantalis.ta_crown_tenures_svw
INFO:bcdata.wfs:Total features requested: 67038
INFO:bcdata.bc2pg:https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_TANTALIS.TA_CROWN_TENURES_SVW&outputFormat=json&SRSNAME=epsg%3A3005&sortby=OBJECTID&startIndex=0&count=10000
INFO:bcdata.bc2pg:Writing WHSE_TANTALIS.TA_CROWN_TENURES_SVW to database as whse_tantalis.ta_crown_tenures_svw
Traceback (most recent call last):
  File "/Users/snorris/miniconda3/envs/bcdataenv/bin/bcdata", line 33, in <module>
    sys.exit(load_entry_point('bcdata', 'console_scripts', 'bcdata')())
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/snorris/Projects/repo/bcdata/bcdata/cli.py", line 332, in bc2pg
    out_table = bcdata.bc2pg(
  File "/Users/snorris/Projects/repo/bcdata/bcdata/bc2pg.py", line 185, in bc2pg
    df.to_postgis(table_name, db.engine, if_exists="append", schema=schema_name)
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.10/site-packages/geopandas/geodataframe.py", line 1808, in to_postgis
    geopandas.io.sql._write_postgis(
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.10/site-packages/geopandas/io/sql.py", line 402, in _write_postgis
    gdf = _convert_to_ewkb(gdf, geom_name, srid)
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.10/site-packages/geopandas/io/sql.py", line 286, in _convert_to_ewkb
    geoms = [dumps(geom, srid=srid, hex=True) for geom in gdf[geom_name]]
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.10/site-packages/geopandas/io/sql.py", line 286, in <listcomp>
    geoms = [dumps(geom, srid=srid, hex=True) for geom in gdf[geom_name]]
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.10/site-packages/shapely/wkb.py", line 57, in dumps
    geom = lgeos.GEOSGeom_clone(ob._geom)
AttributeError: 'NoneType' object has no attribute '_geom'
```

**Comment by smnorris** [comment]
Looks like we need to strip out records with null geometries. ogr2ogr loaded these fine:
```
postgis=# select count(*) from whse_tantalis.ta_crown_tenures_svw where geom is null;
 count
-------
   466
```

**Comment by smnorris** [comment]
yep:
```
>>> df[df['geometry'].isna()]
                                                     id  INTRID_SID  TENURE_STAGE                 TENURE_STATUS  ... FEATURE_LENGTH_M OBJECTID SE_ANNO_CAD_DATA geometry
126   WHSE_TANTALIS.TA_CROWN_TENURES_SVW.fid-25a86ab...      812700  PRE-TANTALIS                        ACTIVE  ...              NaN      127             None     None
381   WHSE_TANTALIS.TA_CROWN_TENURES_SVW.fid-25a86ab...      930100   APPLICATION                      ACCEPTED  ...              NaN      382             None     None
475   WHSE_TANTALIS.TA_CROWN_TENURES_SVW.fid-25a86ab...      951100   APPLICATION                      ACCEPTED  ...              NaN      476             None     None
476   WHSE_TANTALIS.TA_CROWN_TENURES_SVW.fid-25a86ab...      951200   APPLICATION                      ACCEPTED  ...              NaN      477             None     None
526   WHSE_TANTALIS.TA_CROWN_TENURES_SVW.fid-25a86ab...      960600        TENURE  DISPOSITION IN GOOD STANDING  ...              NaN      527             None     None
659   WHSE_TANTALIS.TA_CROWN_TENURES_SVW.fid-25a86ab...      978400   APPLICATION                      ACCEPTED  ...              NaN      660             None     None
661   WHSE_TANTALIS.TA_CROWN_TENURES_SVW.fid-25a86ab...      107998        TENURE  DISPOSITION IN GOOD STANDING  ...              NaN      662             None     None
2101  WHSE_TANTALIS.TA_CROWN_TENURES_SVW.fid-25a86ab...      172193        TENURE  DISPOSITION IN GOOD STANDING  ...              NaN     2102             None     None
2102  WHSE_TANTALIS.TA_CROWN_TENURES_SVW.fid-25a86ab...      172349        TENURE  DISPOSITION IN GOOD STANDING  ...              NaN     2103             None     None
2103  WHSE_TANTALIS.TA_CROWN_TENURES_SVW.fid-25a86ab...      172401        TENURE  DISPOSITION IN GOOD STANDING  ...              NaN     2104             None     None
7669  WHSE_TANTALIS.TA_CROWN_TENURES_SVW.fid-25a86ab...      270626        TENURE  DISPOSITION IN GOOD STANDING  ...              NaN     7670             None     None
```

**Comment by smnorris** [comment]
Not so simple - geopandas represents the null geometry as a geometry collection. Postgis says that this does not match our existing 'MULTIPOLYGON' geometry column. Perhaps load features with geoms with geopandas, and features without geom via pandas?
