### ISSUE TITLE
Handle network or source issues

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#118]
Automated data replication seems to be vulnerable to occasional unexpected errors similar to below. 
Try and handle these - check a response before parsing it, try again a few seconds later if a request fails or if a response is empty.

```
bcdata bc2pg \
	--schema fwapg \
	--query "WATERSHED_GROUP_CODE = 'LSIK'" \
	--append \
	whse_basemapping.fwa_linear_boundaries_sp
Traceback (most recent call last):
  File "/home/snorris/.local/bin/bcdata", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/cli.py", line 357, in bc2pg
    out_table = bcdata.bc2pg(
  File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/bc2pg.py", line 79, in bc2pg
    urls = bcdata.define_requests(
  File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/wfs.py", line 145, in define_requests
    n = bcdata.get_count(table, query=query)
  File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/wfs.py", line 110, in get_count
    return int(ET.fromstring(r.text).attrib["numberMatched"])
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1342, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
make: *** [Makefile:129: .make/fwa_linear_boundaries_sp_LSIK] Error 1
```

**Comment by smnorris** [comment]
c500c7f1755f05f732c8854a4ea70e402a5bfc4d at least catches connection errors in the `get_count` function so connection errors do not lead to above cryptic message.

Before failing entirely, re-trying a few times would be good:
https://realpython.com/python-requests/#max-retries

**Comment by smnorris** [comment]
Note that requests made by `bc2pg` are not handled internally by `bcdata` and `requests` - they are processed by `geopandas.read_file(url)`, using `urllib3.urlopen`.

**Comment by smnorris** [comment]
sample `bc2pg` timeout error:

```
bcdata bc2pg -t \
	--schema fwapg \
	--query "WATERSHED_GROUP_CODE = 'KOTR'" \
	--append \
	whse_basemapping.fwa_stream_networks_sp
INFO:bcdata.wfs:Total features requested: 29535
Traceback (most recent call last):
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='openmaps.gov.bc.ca', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/snorris/miniconda3/envs/bcfishpass/bin/bcdata", line 8, in <module>
    sys.exit(cli())
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/bcdata/cli.py", line 357, in bc2pg
    out_table = bcdata.bc2pg(
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/bcdata/bc2pg.py", line 79, in bc2pg
    urls = bcdata.define_requests(
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/bcdata/wfs.py", line 151, in define_requests
    wfs = WebFeatureService(url=bcdata.OWS_URL, version="2.0.0")
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/owslib/wfs.py", line 56, in WebFeatureService
    return wfs200.WebFeatureService_2_0_0(
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/owslib/feature/wfs200.py", line 77, in __new__
    obj.__init__(
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/owslib/feature/wfs200.py", line 128, in __init__
    self._capabilities = reader.read(self.url, self.timeout)
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/owslib/feature/common.py", line 54, in read
    u = openURL(request, timeout=timeout, headers=self.headers, auth=self.auth)
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/owslib/util.py", line 208, in openURL
    req = requests.request(method.upper(), url_base, headers=headers, **rkwargs)
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.9/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='openmaps.gov.bc.ca', port=80): Read timed out. (read timeout=30)
```

**Comment by smnorris** [comment]
The default 30s may simply be too low. But I'm not sure why `requests` errors are showing up when the processing is done by the stdlib. Might be easier to debug by making the requests in `bcdata` rather than farming out to `geopandas`.
