### ISSUE TITLE
database connection broken with sqlalchemy 2

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcdata#124]
Using pip version I am able to run other commands (ex. `cat`) but not `bc2pg`.  The same scripts run fine from an interactive terminal.  Useing `bash -l `switches to get `bcdata` to fire but the `bc2pg` command fails.  Tried different tables with same result.

Any familiarity with this behaviour?  Have you had success running the command from outside? Thinking it might be a glitch related to my setup config.  

```
bcdata bc2pg WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW -s
INFO:bcdata.wfs:Getting feature geometry type
INFO:bcdata.wfs:Total features requested: 10
INFO:bcdata.wfs:https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW&outputFormat=json&SRSNAME=epsg%3A4326&count=10
Traceback (most recent call last):
  File "/home/airvine/.local/bin/bcdata", line 8, in <module>
    sys.exit(cli())
  File "/home/airvine/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/airvine/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/airvine/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/airvine/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/airvine/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/airvine/.local/lib/python3.8/site-packages/bcdata/cli.py", line 357, in bc2pg
    out_table = bcdata.bc2pg(
  File "/home/airvine/.local/lib/python3.8/site-packages/bcdata/bc2pg.py", line 59, in bc2pg
    table = db.define_table(
  File "/home/airvine/.local/lib/python3.8/site-packages/bcdata/database.py", line 153, in define_table
    meta = MetaData(bind=self.engine)
TypeError: __init__() got an unexpected keyword argument 'bind'
make: Leaving directory '/home/airvine/config'
make: *** [Makefile:20: .make/setup] Error 1
Error: ssh failed
chmod 0700 config/test.sh && bash -l -c config/test.sh
```

**Comment by NewGraphEnvironment** [comment]
actually getting this same error now on a fresh install on calls to `bc2pg` from the command line on the virtual machine. Has to be something in the mother computers configuration I am thinking because I have other brand new machines where it is working fine.  Thought this setup was equivalent to the one before but must have a nuance... Darn. Too bad the messaging is so cryptic. 

Tried reinstalling conda according to [this](https://waylonwalker.com/install-miniconda/) and rebuilding the virtual environment to no prevail.

**Comment by smnorris** [comment]
What versions of bcdata and sqlalchemy are installed? Find them with these commands:

`$ bcdata --version`

```
$ python 
>>> import sqlalchemy
>>> sqlalchemy.__version__
```

**Comment by smnorris** [comment]
Yes, it looks like a `sqlalchemy` issue - I get the same error if creating a fresh environment.
I'll have to pin it to <v2 in the conda environment definition.

**Comment by smnorris** [comment]
the migration docs are extensive, I'll just pin to v1.4 for now
https://docs.sqlalchemy.org/en/20/changelog/migration_20.html

**Comment by smnorris** [comment]
I've cut a new release (0.7.6) - it should now work fine.

**Comment by NewGraphEnvironment** [comment]
`pip install bcdata`

```
Installing collected packages: sqlalchemy, bcdata
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.0
    Uninstalling SQLAlchemy-2.0.0:
      Successfully uninstalled SQLAlchemy-2.0.0
Successfully installed bcdata-0.7.6 sqlalchemy-1.4.46
```

Amazing. Thank you!

**Comment by NewGraphEnvironment** [comment]
Interestingly (and potentially of utility for more permanent fix) we get the exact same error from `sqlalchemy-1.4.46` when we try to run `bc2pg` from a non-interactive shell.... First 


```
+     # bash -l will run script as though it had been invoked as a login shell
+     "chmod 0777 config/test.sh && bash -l -c config/test.sh") # 
[100%] /Users/airvine/Projects/repo/setup-2022/scripts/config/test.sh
./config/
+ source /home/airvine/miniconda3/etc/profile.d/conda.sh
++ export CONDA_EXE=/home/airvine/miniconda3/bin/conda
++ CONDA_EXE=/home/airvine/miniconda3/bin/conda
++ export _CE_M=
++ _CE_M=
++ export _CE_CONDA=
++ _CE_CONDA=
++ export CONDA_PYTHON_EXE=/home/airvine/miniconda3/bin/python
++ CONDA_PYTHON_EXE=/home/airvine/miniconda3/bin/python
++ '[' -z '' ']'
++ export CONDA_SHLVL=0
++ CONDA_SHLVL=0
++ '[' -n '' ']'
++++ dirname /home/airvine/miniconda3/bin/conda
+++ dirname /home/airvine/miniconda3/bin
++ PATH=/home/airvine/miniconda3/condabin:/home/airvine/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
++ export PATH
++ '[' -z '' ']'
++ PS1=
+ conda run --name newgraph
+ local cmd=run
+ case "$cmd" in
+ __conda_exe run --name newgraph
+ /home/airvine/miniconda3/bin/conda run --name newgraph
WARNING: overwriting environment variables set in the machine
overwriting variable {'PGDATABASE', 'PGUSER', 'PGPORT', 'PGHOST', 'DATABASE_URL'}

+ bcdata bc2pg bc-airports
INFO:bcdata.wfs:Getting feature geometry type
INFO:bcdata.wfs:Total features requested: 10
INFO:bcdata.wfs:https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW&outputFormat=json&SRSNAME=epsg%3A4326&count=10
Traceback (most recent call last):
  File "/home/airvine/.local/bin/bcdata", line 8, in <module>
    sys.exit(cli())
  File "/home/airvine/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/airvine/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/airvine/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/airvine/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/airvine/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/airvine/.local/lib/python3.8/site-packages/bcdata/cli.py", line 357, in bc2pg
    out_table = bcdata.bc2pg(
  File "/home/airvine/.local/lib/python3.8/site-packages/bcdata/bc2pg.py", line 59, in bc2pg
    table = db.define_table(
  File "/home/airvine/.local/lib/python3.8/site-packages/bcdata/database.py", line 153, in define_table
    meta = MetaData(bind=self.engine)
TypeError: __init__() got an unexpected keyword argument 'bind'
Error: ssh failed
chmod 0777 config/test.sh && bash -l -c config/test.sh
```

**Comment by smnorris** [comment]
it must be using sqlalchemy 2 if producing that error
