### ISSUE TITLE
download from url fails with geopandas 0.13.0

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#129]
error:

```
$ python
Python 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:58:31) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import geopandas
>>> df = geopandas.read_file("https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW&outputFormat=json&SRSNAME=epsg%3A3005&count=455")
Traceback (most recent call last):
  File "fiona/ogrext.pyx", line 136, in fiona.ogrext.gdal_open_vector
  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: '/vsicurl/https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW&outputFormat=json&SRSNAME=epsg%3A3005&count=455' not recognized as a supported file format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.11/site-packages/geopandas/io/file.py", line 248, in _read_file
    return _read_file_fiona(
           ^^^^^^^^^^^^^^^^^
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.11/site-packages/geopandas/io/file.py", line 289, in _read_file_fiona
    with reader(path_or_bytes, **kwargs) as features:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.11/site-packages/fiona/env.py", line 457, in wrapper
    return f(*args, **kwds)
           ^^^^^^^^^^^^^^^^
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.11/site-packages/fiona/__init__.py", line 292, in open
    colxn = Collection(
            ^^^^^^^^^^^
  File "/Users/snorris/miniconda3/envs/bcdataenv/lib/python3.11/site-packages/fiona/collection.py", line 243, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 588, in fiona.ogrext.Session.start
  File "fiona/ogrext.pyx", line 143, in fiona.ogrext.gdal_open_vector
fiona.errors.DriverError: '/vsicurl/https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW&outputFormat=json&SRSNAME=epsg%3A3005&count=455' not recognized as a supported file format.
```

key dependencies from `conda list`:
```
fiona                     1.9.4           py311h0e2296b_0    conda-forge
gdal                      3.7.0           py311h58e9056_0    conda-forge
geoalchemy2               0.13.3             pyhd8ed1ab_0    conda-forge
geopandas                 0.13.0             pyhd8ed1ab_0    conda-forge
pandas                    2.0.2           py311h9e438b8_0    conda-forge
```

command works fine in another environment with these version of dependencies:

```
fiona                     1.8.22          py311habcf648_5    conda-forge
gdal                      3.6.3           py311h43bd5d3_1    conda-forge
geoalchemy2               0.13.1             pyhd8ed1ab_0    conda-forge
geopandas                 0.12.2             pyhd8ed1ab_0    conda-forge
pandas                    1.5.3           py311h4eec4a9_0    conda-forge
```

**Comment by smnorris** [comment]
this works fine in both environments, maybe it is a fiona issue:
```
ogrinfo "https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW&outputFormat=json&SRSNAME=epsg%3A3005&count=455"
```

**Comment by smnorris** [comment]
Looks like it is a geopandas issue:

https://github.com/geopandas/geopandas/issues/2908

**Comment by smnorris** [comment]
pinned to < v0.13 until this is resolved upstream.
