### ISSUE TITLE
bc2pg fails on WHSE_MINERAL_TENURE.OG_ROAD_SEGMENT_PERMIT_SP

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#131]
```
$ bcdata bc2pg WHSE_MINERAL_TENURE.OG_ROAD_SEGMENT_PERMIT_SP
INFO:bcdata.wfs:Getting feature geometry type
INFO:bcdata.wfs:Total features requested: 10
INFO:bcdata.wfs:https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_MINERAL_TENURE.OG_ROAD_SEGMENT_PERMIT_SP&outputFormat=json&SRSNAME=epsg%3A4326&count=10
WARNING:bcdata.wfs:Dataset WHSE_MINERAL_TENURE.OG_ROAD_SEGMENT_PERMIT_SP has multiple geometry types: MULTILINESTRING,LINESTRING
Traceback (most recent call last):
  File "/Users/snorris/Projects/repo/bcdata/bcdata_env/bin/bcdata", line 8, in <module>
    sys.exit(cli())
  File "/Users/snorris/Projects/repo/bcdata/bcdata_env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/snorris/Projects/repo/bcdata/bcdata_env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/snorris/Projects/repo/bcdata/bcdata_env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/snorris/Projects/repo/bcdata/bcdata_env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/snorris/Projects/repo/bcdata/bcdata_env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/snorris/Projects/repo/bcdata/bcdata/cli.py", line 367, in bc2pg
    out_table = bcdata.bc2pg(
  File "/Users/snorris/Projects/repo/bcdata/bcdata/bc2pg.py", line 56, in bc2pg
    geom_type = bcdata.get_types(dataset, 10)[0]
  File "/Users/snorris/Projects/repo/bcdata/bcdata/wfs.py", line 343, in get_types
    and len(features[0]["geometry"]["coordinates"][0][0]) == 3
TypeError: object of type 'float' has no len()
```

**Comment by smnorris** [comment]
Looks like the check for Z dimension always checks the first record. 
When a dataset has mixed types, this first record may not match the type expected in line 343, the index used for checking the coordinates is incorrect if type is incorrect.
