### ISSUE TITLE
bc2pg fails accessing water-rights-applications-public using bc2pg

### ISSUE THREAD

**Issue by haileye** [smnorris/bcdata#132]
When trying to use bc2pg to import `water-rights-applications-public` (url: https://catalogue.data.gov.bc.ca/dataset/water-rights-applications-public), run into the following error:
```
INFO:bcdata.wfs:Getting feature geometry type
INFO:bcdata.wfs:Total features requested: 10
INFO:bcdata.wfs:https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_WATER_MANAGEMENT.WLS_WATER_RIGHTS_APPLICTNS_SV&outputFormat=json&SRSNAME=epsg%3A4326&count=10
Traceback (most recent call last):
  File "/opt/venvs/test/bin/bcdata", line 8, in <module>
    sys.exit(cli())
  File "/opt/venvs/test/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venvs/test/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venvs/test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venvs/test/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venvs/test/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/venvs/test/lib/python3.8/site-packages/bcdata/cli.py", line 367, in bc2pg
    out_table = bcdata.bc2pg(
  File "/opt/venvs/test/lib/python3.8/site-packages/bcdata/bc2pg.py", line 56, in bc2pg
    geom_type = bcdata.get_types(dataset, 10)[0]
IndexError: list index out of range
```

**Comment by smnorris** [comment]
Thanks for reporting.  Can confirm same issue here with v0.7.9:
```
$ bcdata --version
0.7.9

$ bcdata bc2pg WHSE_WATER_MANAGEMENT.WLS_WATER_RIGHTS_APPLICTNS_SV -db postgresql://postgres@localhost:5432/postgis
INFO:bcdata.wfs:Getting feature geometry type
INFO:bcdata.wfs:Total features requested: 10
INFO:bcdata.wfs:https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_WATER_MANAGEMENT.WLS_WATER_RIGHTS_APPLICTNS_SV&outputFormat=json&SRSNAME=epsg%3A4326&count=10
Traceback (most recent call last):
  File "/Users/snorris/miniconda3/envs/bcfishpass/bin/bcdata", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.11/site-packages/bcdata/cli.py", line 367, in bc2pg
    out_table = bcdata.bc2pg(
                ^^^^^^^^^^^^^
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.11/site-packages/bcdata/bc2pg.py", line 56, in bc2pg
    geom_type = bcdata.get_types(dataset, 10)[0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by haileye** [comment]
The error I reported was also with bcdata version 0.7.9

**Comment by smnorris** [comment]
No geometry is present in the first 10 records in that dataset, spatial type guessing is not going to work as is - and AFAIK there is no other way to determine the spatial type that will be returned for a given request - `bcdata info` can ask the Catalogue API for all the details about a table but this is not very helpful:
```{"column_name": "SHAPE", "data_type": "SDO_GEOMETRY", "column_comments": "SHAPE is the column used to reference the spatial coordinates defining the feature.", "short_name": "SHAPE", "data_precision": "64"}
```
Potential work arounds:
- change default request from 10 to maybe 100(?) features when examining spatial types
- add option to `bc2pg` for user specified sample size when examining types
- add option to `bc2pg` for user to specify the spatial type

**Comment by smnorris** [comment]
Or potentially filter out records with no geometry in your request. I'm not sure if that is actually possible, but worth a shot.

**Comment by haileye** [comment]
I vote

- add option to bc2pg for user to specify the spatial type

I also like the option of filtering out records with no geometry (as that is a necessary post processing step for me anyways) but has potential for confusing results for users as the returned data could be incomplete

**Comment by smnorris** [comment]
Agreed, that is tidiest.  

On further review, another option could be have `geopandas` assign the spatial type based on the first full response and just remove the `wfs.get_types` function entirely. Handling `bc2pg --schema_only` would get fussier then though.

**Comment by haileye** [comment]
I'm not sure of the intricacies there - why would it become fussier?

**Comment by smnorris** [comment]
It might be a simple re-arrangement of the code but currently data is only loaded to geopandas if the `schema_only` option is not specified:

https://github.com/smnorris/bcdata/blob/main/bcdata/bc2pg.py#L77

Also, it looks like null geoms are already dropped before load, you shouldn't have to do this in post-processing anymore:
https://github.com/smnorris/bcdata/blob/main/bcdata/bc2pg.py#L104
