### ISSUE TITLE
incomplete read / 503 / etc 

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#136]
command:
`bcdata bc2pg WHSE_FOREST_VEGETATION.OGSR_PRIORITY_DEF_AREA_CUR_SP`

error:
```
INFO:bcdata.bc2pg:https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_FOREST_VEGETATION.OGSR_PRIORITY_DEF_AREA_CUR_SP&outputFormat=json&SRSNAME=epsg%3A3005&sortby=OBJECTID&startIndex=120000&count=10000
Traceback (most recent call last):
  File "/usr/lib/python3.10/http/client.py", line 565, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.10/http/client.py", line 532, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/http/client.py", line 582, in _read_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.10/http/client.py", line 567, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/snorris/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/bc2pg.py", line 37, in _download
    return gpd.read_file(url)
  File "/home/snorris/.local/lib/python3.10/site-packages/geopandas/io/file.py", line 267, in _read_file
    filename = response.read()
  File "/usr/lib/python3.10/http/client.py", line 459, in read
    return self._read_chunked(amt)
  File "/usr/lib/python3.10/http/client.py", line 597, in _read_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(957209 bytes read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/snorris/.local/bin/bcdata", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/cli.py", line 369, in bc2pg
    out_table = bcdata.bc2pg(
  File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/bc2pg.py", line 122, in bc2pg
    df = _download(url)
  File "/home/snorris/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/snorris/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/snorris/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7fc5e1f98100 state=finished raised IncompleteRead>]
```

**Comment by smnorris** [comment]
- use `requests` instead ?
- wrap `geopandas.read_file(url)` in a `try`?

**Comment by smnorris** [comment]
`get_count` fails too:
```
DEBUG:bcdata.wfs:https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_FOREST_VEG
ETATION.OGSR_PRIORITY_DEF_AREA_CUR_SP&resultType=hits&outputFormat=json
Traceback (most recent call last):
  File "/home/snorris/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/wfs.py", line 128, in get_count
    r.raise_for_status()  # check status code is 200
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error:  for url: https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&r
equest=GetFeature&typeName=WHSE_FOREST_VEGETATION.OGSR_PRIORITY_DEF_AREA_CUR_SP&resultType=hits&outputFormat=json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/snorris/.local/bin/bcdata", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/cli.py", line 369, in bc2pg
    out_table = bcdata.bc2pg(
  File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/bc2pg.py", line 92, in bc2pg
    geometry_type = bcdata.get_types(dataset, 10)[0]
  File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/wfs.py", line 312, in get_types
    for f in get_features(table, count=count):
  File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/wfs.py", line 286, in get_features
    urls = define_requests(
  File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/wfs.py", line 152, in define_requests
    n = bcdata.get_count(table, query=query)
  File "/home/snorris/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/snorris/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/snorris/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f865a876b90 state=finished raised HTTPError>]
```

**Comment by smnorris** [comment]
Not catching any errors so far. Closing for now...
