### ISSUE TITLE
WFS._request_features returns NoneType

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#138]
It looks like the service is returning a 200 but no features. 
Verbose logging might be required to see exactly what the issue is.
```
bcdata bc2pg WHSE_FISH.FISS_FISH_OBSRVTN_PNT_SP -e
2023-07-22 08:00:17,692:INFO:bcdata.wfs: Getting feature geometry type
2023-07-22 08:00:17,692:INFO:bcdata.wfs: Total features requested: 10
Traceback (most recent call last):
File "/home/snorris/.local/bin/bcdata", line 8, in <module>
 sys.exit(cli())
File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
 return self.main(*args, **kwargs)
File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
 rv = self.invoke(ctx)
File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
 return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
 return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
 return __callback(*args, **kwargs)
File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/cli.py", line 378, in bc2pg
 out_table = bcdata.bc2pg(
File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/bc2pg.py", line 97, in bc2pg
 geometry_type = bcdata.get_spatial_types(dataset, 10)[0]
File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/wfs.py", line 513, in get_spatial_types
 return WFS.get_spatial_types(dataset, count=count)
File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/wfs.py", line 384, in get_spatial_types
 for f in self.get_features(
File "/home/snorris/.local/lib/python3.10/site-packages/bcdata/wfs.py", line 369, in get_features
 for feature in self._request_features(url):
TypeError: 'NoneType' object is not iterable
```

**Comment by smnorris** [comment]
all WFS requests now wrapped by `retry`
