### ISSUE TITLE
national parks fails

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#15]
`bcdata national-parks-national-framework-canada-lands-administrative-boundaries-level-1`

```
Traceback (most recent call last):
  File "/usr/local/bin/bcdata", line 9, in <module>
    load_entry_point('bcdata', 'console_scripts', 'bcdata')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Volumes/Data/Projects/geobc/bcdata/bcdata/scripts/cli.py", line 65, in cli
    geomark=geomark)
  File "/Volumes/Data/Projects/geobc/bcdata/bcdata/__init__.py", line 60, in create_order
    custom_download_link.click()
UnboundLocalError: local variable 'custom_download_link' referenced before assignment
```

**Comment by smnorris** [comment]
this one fails too `natural-resource-nr-regions`

something wrong in how the custom download link is found
