### ISSUE TITLE
should other commands in the CLI include data cleaning as per bc2pg?

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#175]
Writing to file via `bcdata cat` is error prone due to the mixed types in the response. 
Should the stream of features be cleaned as per `bc2pg`?

```
$ bcdata cat WHSE_FOREST_TENURE.FTEN_ROAD_SECTION_LINES_SVW \
  --query "LIFE_CYCLE_STATUS_CODE = 'RETIRED'" \
  --dst-crs EPSG:3005 \
  | fio collect \
  | fio load -f OpenFileGDB --dst-crs EPSG:3005 ften_retired.gdb
ERROR:fiona.fio.load:Exception caught during processing
Traceback (most recent call last):
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.11/site-packages/fiona/fio/load.py", line 117, in load
    dst.writerecords(source)
  File "/Users/snorris/miniconda3/envs/bcfishpass/lib/python3.11/site-packages/fiona/collection.py", line 361, in writerecords
    self.session.writerecs(records, self)
  File "fiona/ogrext.pyx", line 1285, in fiona.ogrext.WritingSession.writerecs
fiona.errors.GeometryTypeValidationError: Record's geometry type does not match collection schema's geometry type: 'MultiLineString' != 'LineString'
Aborted!
```

**Comment by smnorris** [comment]
Could be useful - but probably simpler to write python scripts as needed, with `get_data(as_gdf=True)` and doing the cleaning/write to file with geopandas. Might be an issue on memory limited systems.

**Comment by smnorris** [comment]
Thinking about this more, `cat` should probably just stream features as supplied by the service.
Defining the output schema with `fio` would help, this is noted in the source as maybe a todo:
https://github.com/Toblerity/Fiona/blob/main/fiona/fio/load.py#L84
To further clean:
- `jq` could probably filter out records with null geometries
- cast to multipart via a shapely script?

**Comment by smnorris** [comment]
Yep - `dump g` is the ticket:
```
bcdata cat WHSE_FOREST_TENURE.FTEN_ROAD_SECTION_LINES_SVW   \
  --query "LIFE_CYCLE_STATUS_CODE = 'RETIRED'" \
  --dst-crs EPSG:3005   \
 | fio map 'dump g' \
 | fio load -f GPKG example.gpkg
```
