### ISSUE TITLE
download times out too soon

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#19]
```
bcdata tantalis-management-areas-spatial
Traceback (most recent call last):
  File "/usr/local/bin/bcdata", line 9, in <module>
    load_entry_point('bcdata', 'console_scripts', 'bcdata')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Volumes/Data/Projects/geobc/bcdata/bcdata/scripts/cli.py", line 69, in cli
    dl_path = bcdata.download_order(order_id)
  File "/Volumes/Data/Projects/geobc/bcdata/bcdata/__init__.py", line 144, in download_order
    raise RuntimeError("Download for order_id "+order_id+" timed out")
RuntimeError: Download for order_id 1662791 timed out
```

**Comment by smnorris** [comment]
this was probably a DWDS issue, most downloads seem fine
