### ISSUE TITLE
dump fails when providing both bounds and a query

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#58]
The `dump` tool will not accept both bounds and a query:

this works:
```
$ bcdata dump \
WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW \
--query "AIRPORT_NAME='Victoria International Airport'"
```

as does this:
```
$ bcdata dump \
WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW \
--bounds "1167680.0 367958.0 1205720.0 432374.0"
```

But this fails:
```
$ bcdata dump \
WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW \
--query "AIRPORT_NAME='Victoria International Airport'" \
--bounds "1167680.0 367958.0 1205720.0 432374.0"
Traceback (most recent call last):
  File "/usr/local/bin/bcdata", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/bcdata/cli.py", line 175, in dump
    data = bcdata.get_data(table, query=query, bounds=bounds)
  File "/usr/local/lib/python3.7/site-packages/bcdata/wfs.py", line 196, in get_data
    for result in results:
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/bcdata/wfs.py", line 126, in make_request
    return r.json()["features"]
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by smnorris** [comment]
from the WFS spec: `BBOX (Mutually exclusive with FEATUREID and FILTER.)`

https://www.opengeospatial.org/standards/wfs
http://portal.opengeospatial.org/files/?artifact_id=8339

To combine bbox and a filter, the request has to create a filter that contains both bbox and the query rather than using separate parameters.

**Comment by smnorris** [comment]
This works, the trick will be identifying the geometry column and making sure the coordinates are the right projection:
```
$ bcdata dump WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW --query "AIRPORT_NAME='Victoria International Airport' AND bbox(SHAPE, 1167680.0, 367958.0, 1205720.0, 432374.0)"
```

**Comment by smnorris** [comment]
fixed with https://github.com/smnorris/bcdata/commit/42b138d11e0949b481843190402ae4f34c918b32 (issue incorrectly tagged in commit message)
