### ISSUE TITLE
SSL Error 

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#59]
https requests to openmaps.gov.bc.ca using Python/requests are failing. 

Python 3.7.4
requests   2.22.0
certifi   2019.9.11

```
>>> requests.get('https://openmaps.gov.bc.ca')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openmaps.gov.bc.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='openmaps.gov.bc.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))
```

**Comment by smnorris** [comment]
We could just make requests over plain http, that works:
```
>>> import requests
>>> requests.get('http://openmaps.gov.bc.ca')
<Response [200]>
```

**Comment by wburt** [comment]
Would be interested in knowing the correct way to fix this problem with a certificate.  I have tried but always end up switching to `requests.get(url,verify=False)`

Not great

**Comment by smnorris** [comment]
Yeah, my understanding of just how the certs work is limited - I've done that workaround for other projects too. But since https worked for bcdata just fine until today, I'm presuming something changed on the server end and will wait a bit before removing https / verification

**Comment by smnorris** [comment]
Note that accessing https://openmaps.gov.bc.ca still works fine via gdal and via the R bcdata package. 
I wonder about using the built-in `urllib` instead of `requests`

**Comment by wburt** [comment]
also works fine with web browser which includes certificate for verification.  So probably bcgov is now requiring ssl as did arcgis online last year. Requests allows you to use something called certify to do this but I haven't had time to get that to work yet.

**Comment by smnorris** [comment]
updating certify and pointing to `cacert.pem` given by `certifi.where()` did not help. 
Checking the ssl report for https://openmaps.gov.bc.ca as given in that SO link results in "This server's certificate chain is incomplete. Grade capped to B", as noted in the SO link. But if this is the issue, downloading the right certificate and pointing to it isn't really what I want to require of users...

**Comment by cetooley** [comment]
might be related to this: https://stackoverflow.com/questions/38522939/requests-exceptions-sslerror-ssl-certificate-verify-failed-certificate-verif 

i.e. requests' certs are pinned per version and are sourced from mozilla, they might be out of date

**Comment by smnorris** [comment]
looks like it is not a requests issue, urllib gives the same result.

```
$ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.request
>>> f = urllib.request.urlopen('https://openmaps.gov.bc.ca')
Traceback (most recent call last):
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Users/snorris/miniconda3/envs/bcdatatest/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
```

**Comment by smnorris** [comment]
Note that I'm on OSX, but have tested with python from `conda` and `brew` - so I don't *think* that the OS would be the issue (2nd answer here), because I'm not using the built-in Python and have certifi installed: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

**Comment by ateucher** [comment]
They may have fixed something on the server, this is working for me now:

```python
>>> import requests
>>> requests.get("https://openmaps.gov.bc.ca")
<Response [200]>
```

**Comment by wburt** [comment]
Confirmed.  In need to learn how to differentiate between my client side certificate problems and server problems.

**Comment by smnorris** [comment]
Thanks, wouldn't you know it, right when I cut a release. 
I'll revert master to https, and maybe try https for the OWS and WCS requests too.

**Comment by smnorris** [comment]
WCS via https works fine but the OWS request via https fails. 
It looks like this might have something to do with passing certs to `owslib`, but I'm not going down that rabbit hole at this point. https://github.com/geopython/OWSLib/blob/master/owslib/util.py#L794

```
>>> from owslib.wfs import WebFeatureService
>>> wfs = WebFeatureService(url="https://openmaps.gov.bc.ca/geo/ows", version="2.0.0")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 601, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 666, in read_chunked
    self._update_chunk_length()
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 605, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 490, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 694, in read_chunked
    self._original_response.close()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/owslib/wfs.py", line 54, in WebFeatureService
    password=password)
  File "/usr/local/lib/python3.7/site-packages/owslib/feature/wfs200.py", line 69, in __new__
    username=username, password=password)
  File "/usr/local/lib/python3.7/site-packages/owslib/feature/wfs200.py", line 95, in __init__
    self._capabilities = reader.read(self.url)
  File "/usr/local/lib/python3.7/site-packages/owslib/feature/common.py", line 55, in read
    username=self.username, password=self.password)
  File "/usr/local/lib/python3.7/site-packages/owslib/util.py", line 190, in openURL
    **rkwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```
