### ISSUE TITLE
dump is writing all response, not just ['features']

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#60]
Since I rarely use the cli other than bc2pg, issue #43 should really be taken care of...

```$ bcdata dump bc-airports > bc-airports.geojson
$ fio info bc-airports.geojson
ERROR:fiona._env:At line 1, character 2: Unexpected character (')
ERROR:fiona._env:Failed to read GeoJSON data
ERROR:fiona.fio.info:Exception caught during processing
Traceback (most recent call last):
  File "fiona/_shim.pyx", line 66, in fiona._shim.gdal_open_vector
  File "fiona/_err.pyx", line 259, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: Failed to read GeoJSON data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fiona/fio/info.py", line 48, in info
    with fiona.open(input, layer=layer) as src:
  File "/usr/local/lib/python3.7/site-packages/fiona/env.py", line 396, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fiona/__init__.py", line 253, in open
    layer=layer, enabled_drivers=enabled_drivers, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fiona/collection.py", line 159, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 467, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 73, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: Failed to read GeoJSON data
Aborted!
$ head bc-airports.geojson -n 1
{'service': 'WFS', 'version': '2.0.0', 'request': 'GetFeature', 'typeName': 'WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW', 'outputFormat': 'json', 'SRSNAME': 'epsg:4326'}
```

**Comment by smnorris** [comment]
Should log the request, not use print statements to debug 🤪
