### ISSUE TITLE
Click >= 7.0 required for autocomplete

### ISSUE THREAD

**Issue by ateucher** [smnorris/bcdata#64]
I had `click` v6.7 installed, so the requirements of `bcdata` were satisfied... but I got the error: 

```bash
$ bcdata dem --bounds "[1046891, 704778, 1055345, 709629]" -o dem25.tif
Traceback (most recent call last):
  File "/usr/local/bin/bcdata", line 6, in <module>
    from bcdata.cli import cli
  File "/usr/local/lib/python3.7/site-packages/bcdata/cli.py", line 118, in <module>
    "--name", "meta_member", flag_value="name", help="Print the datasource's name."
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 151, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1699, in __init__
    Parameter.__init__(self, param_decls, required=required, **attrs)
TypeError: __init__() got an unexpected keyword argument 'autocompletion'
```

It seems that autocompletion was added in `click 7.0`: https://github.com/pallets/click/issues/966. I updated `click` to v7.0 and it worked

**Comment by smnorris** [comment]
Yes, I need to work on better packaging - thanks for reporting.
