### ISSUE TITLE
Cannot rely on object_name in catalogue record for wfs typeName

### ISSUE THREAD

**Issue by ateucher** [smnorris/bcdata#65]
The wfs doesn't always the `layer_name` property in a record ([here](https://github.com/smnorris/bcdata/blob/28c7c97e7ca778502b1be72b0838ca444548b927/bcdata/wfs.py#L76)): 

```bash
$ bcdata dump natural-resource-nr-district
Traceback (most recent call last):
  File "/usr/local/bin/bcdata", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/bcdata/cli.py", line 184, in dump
    data = bcdata.get_data(table, query=query, bounds=bounds, bounds_crs=bounds_crs)
  File "/usr/local/lib/python3.7/site-packages/bcdata/wfs.py", line 214, in get_data
    pagesize=pagesize,
  File "/usr/local/lib/python3.7/site-packages/bcdata/wfs.py", line 146, in define_request
    table = validate_name(dataset)
  File "/usr/local/lib/python3.7/site-packages/bcdata/wfs.py", line 76, in validate_name
    return bcdc_package_show(dataset)["object_name"]
  File "/usr/local/lib/python3.7/site-packages/bcdata/wfs.py", line 66, in bcdc_package_show
    raise ValueError("{d} is not present in DataBC API list".format(d=package))
ValueError: WHSE_ADMIN_BOUNDARIES.ADM_NR_DISTRICTS_SP is not present in DataBC API list
```

[Nor does it always use the `layer_name` property](https://github.com/bcgov/bcdata/issues/138). I have worked around this by pulling it out of the url in wms resource: https://github.com/bcgov/bcdata/pull/139

**Comment by smnorris** [comment]
I'll apply the same fix and figure out some way to note in the README that the output of `bcdata list` will be more reliable to use as a key than `package_name`

**Comment by smnorris** [comment]
Actually, since this is just a WxS tool, I think it is best to just bail if the user supplies a package with more than one valid resource. So:
```
$ bcdata info forest-development-units
Traceback (most recent call last):
  File "/usr/local/bin/bcdata", line 11, in <module>
    load_entry_point('bcdata', 'console_scripts', 'bcdata')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/snorris/Projects/geobc/bcdata/bcdata/cli.py", line 132, in info
    table = bcdata.validate_name(dataset)
  File "/Users/snorris/Projects/geobc/bcdata/bcdata/wfs.py", line 85, in validate_name
    return bcdc_package_show(dataset)
  File "/Users/snorris/Projects/geobc/bcdata/bcdata/wfs.py", line 75, in bcdc_package_show
    raise ValueError("Package {} includes more than one WFS resource, specify one of the following: \n{}".format(package, "\n".join(layer_names)))
ValueError: Package forest-development-units includes more than one WFS resource, specify one of the following:
WHSE_FOREST_TENURE.FSP_FDU_POLY_SVW
WHSE_FOREST_TENURE.FSP_FDU_POLY_300K_SPG
WHSE_FOREST_TENURE.FSP_FDU_POLY_50K_SPG
```
