### ISSUE TITLE
DRA

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#75]
DRA is now too big to download reliably.
```
bcdata bc2pg WHSE_BASEMAPPING.DRA_DGTL_ROAD_ATLAS_MPAR_SP
INFO:bcdata.cli:ogr2ogr -lco OVERWRITE=YES -lco SCHEMA=whse_basemapping -lco GEOMETRY_NAME=geom -f PostgreSQL PG:host=localhost user=hillcrestgeo dbname=crunchytest port=5432 -t_srs EPSG:3005 -nln dra_dgtl_road_atlas_mpar_sp https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_BASEMAPPING.DRA_DGTL_ROAD_ATLAS_MPAR_SP&outputFormat=json&SRSNAME=epsg%3A4326&sortby=OBJECTID&startIndex=0&count=10000 -lco UNLOGGED=ON -lco SPATIAL_INDEX=NONE
  [####################----------------]   56%  00:12:08ERROR 1: transfer closed with outstanding read data remaining
FAILURE:
Unable to open datasource `https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_BASEMAPPING.DRA_DGTL_ROAD_ATLAS_MPAR_SP&outputFormat=json&SRSNAME=epsg%3A4326&sortby=OBJECTID&startIndex=1190000&count=10000' with the following drivers.
```

**Comment by smnorris** [comment]
UWR can also fail:
```
bcdata bc2pg ungulate-winter-range-approved --db_url postgresql://designatedlands:designatedlands@localhost:5433/designatedlands --schema designatedlands --table src_27_uwr_conditional_harvest --query TIMBER_HARVEST_CODE = 'CONDITIONAL HARVEST ZONE'
INFO:bcdata.cli:ogr2ogr -lco OVERWRITE=YES -lco SCHEMA=designatedlands -lco GEOMETRY_NAME=geom -f PostgreSQL PG:host=localhost user=designatedlands dbname=designatedlands port=5433 password=designatedlands -t_srs EPSG:3005 -nln src_27_uwr_conditional_harvest https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_WILDLIFE_MANAGEMENT.WCP_UNGULATE_WINTER_RANGE_SP&outputFormat=json&SRSNAME=epsg%3A4326&sortby=OBJECTID&CQL_FILTER=TIMBER_HARVEST_CODE+%3D+%27CONDITIONAL+HARVEST+ZONE%27&startIndex=0&count=10000 -lco UNLOGGED=ON -lco SPATIAL_INDEX=NONE
  [################################----]   89%  00:00:07ERROR 1: transfer closed with outstanding read data remaining
FAILURE:
Unable to open datasource `https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_WILDLIFE_MANAGEMENT.WCP_UNGULATE_WINTER_RANGE_SP&outputFormat=json&SRSNAME=epsg%3A4326&sortby=OBJECTID&CQL_FILTER=TIMBER_HARVEST_CODE+%3D+%27CONDITIONAL+HARVEST+ZONE%27&startIndex=180000&count=10000' with the following drivers.
```
Calling with just one worker may help (the default of 5 is probably much to aggressive):
```
$ bcdata bc2pg ungulate-winter-range-approved \
 --db_url postgresql://designatedlands:designatedlands@localhost:5433/designatedlands \
 --schema designatedlands \
 --table src_27_uwr_conditional_harvest \
 --query "TIMBER_HARVEST_CODE = 'CONDITIONAL HARVEST ZONE'" \
 -w 1
INFO:bcdata.cli:ogr2ogr -lco OVERWRITE=YES -lco SCHEMA=designatedlands -lco GEOMETRY_NAME=geom -f PostgreSQL PG:host=localhost user=designatedlands dbname=designatedlands port=5433 password=designatedlands -t_srs EPSG:3005 -nln src_27_uwr_conditional_harvest https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_WILDLIFE_MANAGEMENT.WCP_UNGULATE_WINTER_RANGE_SP&outputFormat=json&SRSNAME=epsg%3A4326&sortby=OBJECTID&CQL_FILTER=TIMBER_HARVEST_CODE+%3D+%27CONDITIONAL+HARVEST+ZONE%27&startIndex=0&count=10000 -lco UNLOGGED=ON -lco SPATIAL_INDEX=NONE
  [####################################]  100%
INFO:bcdata.cli:Indexing geometry
INFO:bcdata.cli:Load of WHSE_WILDLIFE_MANAGEMENT.WCP_UNGULATE_WINTER_RANGE_SP to designatedlands.src_27_uwr_conditional_harvest in postgresql://designatedlands:designatedlands@localhost:5433/designatedlands complete
```

**Comment by NewGraphEnvironment** [comment]
i think I ran into this with the BEC layer - although it is referencing `sqlalchemy`....  

Instead I used `bcdata_download` function from [here](https://github.com/NewGraphEnvironment/fish_passage_bulkley_2020_reporting/blob/master/R/0240-load-bcdata.R) to get it in the db.  Error from prior two attempts pasted below:

```
(bcfpenv) newgraph@MSI:~/scripts/bcfishpass/01_prep/04_channel_width$ bcdata bc2pg WHSE_FOREST_VEGETATION.BEC_BIOGEOCLIMATIC_POLY
INFO:bcdata.cli:ogr2ogr -f PostgreSQL PG:host=localhost user=newgraph dbname=postgis port=5434 password=postgres -t_srs EPSG:3005 -nln whse_forest_vegetation.bec_biogeoclimatic_poly https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_FOREST_VEGETATION.BEC_BIOGEOCLIMATIC_POLY&outputFormat=json&SRSNAME=epsg%3A4326&sortby=OBJECTID&startIndex=0&count=10000 -overwrite -lco GEOMETRY_NAME=geom -lco UNLOGGED=ON -lco SPATIAL_INDEX=NONE

Traceback (most recent call last):
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "whse_forest_vegetation.bec_biogeoclimatic_poly" does not exist
LINE 3:             (LIKE whse_forest_vegetation.bec_biogeoclimatic_...
                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/newgraph/anaconda3/envs/bcfpenv/bin/bcdata", line 8, in <module>
    sys.exit(cli())
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/bcdata/cli.py", line 420, in bc2pg
    conn.execute(sql)
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/pgdata/database.py", line 156, in execute
    result = conn.execute(sql, params)
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/newgraph/anaconda3/envs/bcfpenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "whse_forest_vegetation.bec_biogeoclimatic_poly" does not exist
LINE 3:             (LIKE whse_forest_vegetation.bec_biogeoclimatic_...
                          ^

[SQL: 
            CREATE TABLE whse_forest_vegetation.bec_biogeoclimatic_poly_0
            (LIKE whse_forest_vegetation.bec_biogeoclimatic_poly
            INCLUDING ALL)
            ]
[parameters: (None,)]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by smnorris** [comment]
That isn't a large request issue, something is broken and BEC is not that big, it should download ok (although it does seem a bit slow right now).

I am not sure why you are getting that error, sqlalchemy is not imported in the latest version of bcdata.

I do see that I neglected to update `setup.py` though, I'll fix cut a new release with that fixed but suspect something is off in your environment as well.

**Comment by NewGraphEnvironment** [comment]
Enviro issues seem to be my forte... Haven't had an issue with any other layer though.  Maybe you should see if it works on your machine before you do too much wrenching...

**Comment by smnorris** [comment]
but are any of the other layers >10k records?

**Comment by NewGraphEnvironment** [comment]
yes.  Everything in `bcfishpass` so far except `BEC`

**Comment by smnorris** [comment]
BEC is >10k as well, but I'm not sure what is going on - you shouldn't get that error if you are using the latest.
Try re-installing. You'll get 0.4.5 via pip now:
```
pip uninstall bcdata
pip install bcdata
```

**Comment by NewGraphEnvironment** [comment]
Did you try it and it worked?  I just downloaded the sample site layer 2 seconds ago and that was all good. 

I was just letting you know. I got BEC in the db already using the other bcdata...  I'd rather chase it later if I need if it happens on another layer.

**Comment by smnorris** [comment]
It was a bit slow but worked fine. 
Glad you filed the issue, it made me check requirements and having `setup.py` wrong was definitely an oversight. But I don't think it is related, I suspect it is because you were installing the development version of bcdata and that is somehow conflicting.

**Comment by smnorris** [comment]
This will identify what is going on
`$ bcdata --version` 
and
`$ where bcdata`

**Comment by NewGraphEnvironment** [comment]
ya, i'm on development. I'm terrified to touch anything and have it take me 2 days to unravel some glitch though. I'll wait till it happens again.

**Comment by smnorris** [comment]
Hopefully this is directly related to https://github.com/smnorris/bcdata/issues/96

If most errors are simply from to too many requests, support of resuming failed downloads seems low priority to me.

If resuming failed downloads turns out to be necessary, it should be possible. Logging downloads and resuming at the request where a job failed should be straightforward. But for collections with no primary key it might be tricky to tell exactly where the failure occurred.

**Comment by smnorris** [comment]
UWR and DRA download just fine with `bc2pg` command using default `max_workers=2`.  If a large request fails, maybe try using `max_workers=1`. Throttling the requests when hitting the limit rate should be straightforward when using `bcdata.get_features`, but if the [rate limit info is in the headers](https://docs.geoserver.org/stable/en/user/extensions/controlflow/#per-user-rate-control) it will be fussier to get at with `bc2pg`, which is using gdal to make the requests.
