### ISSUE TITLE
Document installation process on windows

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcdata#85]
this is probably something to do with either my absolute punter like understanding of how my computer works or some daft windows idiosyncrasy but after a fresh install of Python39  I get the error detailed in the attached file.  Any off the top of your head ideas of what might be breaking things?
[bcdata_pip_error.txt](https://github.com/smnorris/bcdata/files/5541766/bcdata_pip_error.txt)

**Comment by smnorris** [comment]
No, installing `rasterio` (and `gdal`) via `pip` is very awkward on windows. Get them installed first and then try `pip install bcdata` again. 

Downloading the pre-compiled binaries from Christoph Gohlke works fine as noted in the rasterio docs: https://rasterio.readthedocs.io/en/latest/installation.html

A bit more involved but smoother once you're familiar with the tool is to install `miniconda` and use the `conda` package manager. https://docs.conda.io/projects/conda/en/latest/user-guide/install/windows.html

My workflow to get bcdata installed on windows (after making sure `conda` is available at the command line) would be something like this (from https://geopandas.org/install.html)

```
conda create -n geo_env
conda activate geo_env
conda config --env --add channels conda-forge
conda config --env --set channel_priority strict
conda install geopandas
conda install rasterio
pip install bcdata
```

**Comment by NewGraphEnvironment** [comment]
Thanks for the help so far. Creating a virtual env and installing geopandas/rasterio with conda worked. 

Now, I am able to pull records to postgres when I specify the URL . Sweet action when I run

`(geo_env) C:\scripts>bcdata bc2pg bc-airports --db_url postgresql://postgres:postgres@localhost:5432/postgis`

Now, I am trying to set the environmental variable as per the configuration instructions in https://github.com/smnorris/pgdata . 
I also tried editing the system variable directly (with and without quotes) with the same result. 

I also tried 
engine = create_engine('postgresql://postgres:postgres@localhost:5432/postgis') 
as per 
https://docs.sqlalchemy.org/en/14/core/engines.html#postgresql but perhaps I will wait to run through my steps there till after I hear back whether I am missing something obvious with the direct env variable set and this one below which resulted in equivalent cmd output

(geo_env) C:\scripts>SET DATABASE_URL="postgresql://postgres:postgres@localhost:5432/postgis"

(geo_env) C:\scripts>echo %DATABASE_URL%
"postgresql://postgres:postgres@localhost:5432/postgis"

(geo_env) C:\scripts>bcdata bc2pg bc-airports
Traceback (most recent call last):
  File "c:\users\allan\.conda\envs\geo_env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\allan\.conda\envs\geo_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\allan\.conda\envs\geo_env\Scripts\bcdata.exe\__main__.py", line 7, in <module>
  File "c:\users\allan\.conda\envs\geo_env\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\allan\.conda\envs\geo_env\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\allan\.conda\envs\geo_env\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\allan\.conda\envs\geo_env\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\allan\.conda\envs\geo_env\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\allan\.conda\envs\geo_env\lib\site-packages\bcdata\cli.py", line 350, in bc2pg
    conn = pgdata.connect(db_url)
  File "c:\users\allan\.conda\envs\geo_env\lib\site-packages\pgdata\__init__.py", line 20, in connect
    return Database(url, schema, sql_path=sql_path, multiprocessing=multiprocessing)
  File "c:\users\allan\.conda\envs\geo_env\lib\site-packages\pgdata\database.py", line 41, in __init__
    self.engine = create_engine(url)
  File "c:\users\allan\.conda\envs\geo_env\lib\site-packages\sqlalchemy\engine\__init__.py", line 500, in create_engine
    return strategy.create(*args, **kwargs)
  File "c:\users\allan\.conda\envs\geo_env\lib\site-packages\sqlalchemy\engine\strategies.py", line 54, in create
    u = url.make_url(name_or_url)
  File "c:\users\allan\.conda\envs\geo_env\lib\site-packages\sqlalchemy\engine\url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "c:\users\allan\.conda\envs\geo_env\lib\site-packages\sqlalchemy\engine\url.py", line 290, in _parse_rfc1738_args
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string '"postgresql://postgres:postgres@localhost:5432/postgis"'

I also tried `(geo_env) C:\scripts>SET DATABASE_URL="postgresql://postgres@localhost:5432/postgis"` to try to match the format of https://docs.sqlalchemy.org/en/14/core/engines.html#postgresql  but that was also the same

Sorry for the hassles.

**Comment by smnorris** [comment]
Try 
`SET DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgis`
